server:
  port: 8016

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/wanted
    username: root
    password: preonboarding

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true
        show_sql: true
        highlight_sql: true

logging.level.org:
  hibernate:
    type:
      descriptor:
        sql: trace